### ISSUE TITLE
Aucune entité remontée

### ISSUE THREAD

**Issue by jffz** [max5962/prixCarburant-home-assistant#15]
Aucune entitée ne remonte chez moi malgrés que l'integration soit bien chargée.

```sh
> grep -i carbur home-assistant.log
2022-01-26 14:30:08 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration prixCarburant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

```yml
- platform: prixCarburant
  #maxDistance: 20
  stationID:
    - 33000005
    - 33000003
```
